name: SAST, SCA & SBOM Scan

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  # ----------------------
  # SAST: Semgrep
  # ----------------------
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

  # ----------------------
  # SCA: Dependabot (with details + fail)
  # ----------------------
  sca-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci

      - name: Run Dependabot SCA
        id: dep
        uses: github/dependabot-action@v1
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Vulnerability Details
        run: |
          echo "Dependabot found ${{ steps.dep.outputs.vulnerability-count }} vulnerabilities:"
          echo ""
          echo "${{ steps.dep.outputs.vulnerabilities }}"
        if: steps.dep.outputs.vulnerability-count > 0

      - name: Fail on Vulnerabilities
        run: exit 1
        if: steps.dep.outputs.vulnerability-count > 0

      - name: SCA Passed
        run: echo "No vulnerable dependencies found"
        if: steps.dep.outputs.vulnerability-count == 0

  # ----------------------
  # SBOM: cdxgen
  # ----------------------
  sbom-generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - name: Install cdxgen
        run: npm install -g @cyclonedx/cdxgen
      - name: Generate SBOM
        run: cdxgen -o sbom.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json